window.jQuery = $ = require('jquery');
Tether = require('tether');
UAparser = require('ua-parser-js');
require('./open');
require('./bootstrap');
require('./blockoldbrowsers');
require('./loading');
require('./typekit');
require('./bstab');
require('./suiranfes-updates');
require('./snses');
require('./inputfocus');
require('./jquery-yycountdown');