window.jQuery = $ = require('jquery');
Tether = require('tether');
require('./open');
require('./bootstrap');
require('./blockoldandro');
require('./loading');
require('./typekit');
require('./bstab');
require('./suiranfes-updates');
require('./snses');